# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-Format-RFC3339
version:      v1.0.1
version_from: lib/DateTime/Format/RFC3339.pm
installdirs:  site
requires:
    DateTime:                      0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
